run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: gitlab.com/agneum/plan-exporter
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    line-length: 140
    tab-width: 1
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 20
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  gocritic:
    enabled-tags:
      - performance
  funlen:
    lines: 70

linters:
  enable:
    - depguard
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unused
    - unparam
    - wsl
  enable-all: false
  disable:
    - gosec
    - interfacer
    - gocyclo # currently unmaintained

  presets:
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - errcheck
        - wsl
        - gomnd

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
